version: '3.8'

services:
  moni-thor-bot-container:
   image: bot-container/moni-thor
   build:
    context: .
    dockerfile: dockerfile.dev
   working_dir: /bot-container
   restart: "no"
   expose:
     - 3000
  
  mongo-development:
   image: mongo
   volumes:
     - ./.volumes/.mongodb-storage:/data/db
   expose:
     - 27017
   environment:
     - MONGO_INITDB_ROOT_USERNAME=user
     - MONGO_INITDB_ROOT_PASSWORD=pass
     - MONGO_INITDB_DATABASE=discord_cubos_bot
   restart: always
   